node {
  stage('========== Clone repository ==========') {
    checkout scm
  }
  stage('========== Build image ==========') {
    app = docker.build("acoursove2/k3s_backend_f")
  }
  stage('========== Push image ==========') {
    docker.withRegistry('https://registry.hub.docker.com', '1d20a754-2260-44cf-8078-860eedcf7fe6') {
      app.push("${env.BUILD_NUMBER}")
      app.push("latest")
    }
  }
}
